
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"  
    open-pull-requests-limit: 10
    labels:
      - "type:maintenance"
      - "dependencies"
      - "pr:e2e"
      - "pr:daveit"
      - "pr:visual"
      - "pr:platform"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"    
    labels:
      - "type:maintenance"
      - "dependencies"
      - "pr:daveit"
