
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"  
    open-pull-requests-limit: 10
    labels:
      - "pr:e2e"
      - "type:maintenance"
      - "dependencies"
      - "pr:daveit"
      - "pr:platform"
    ignore:
        #We have to source the container which is not detected by Dependabot
      - dependency-name: "@playwright/test"
        #Lots of noise in these type patch releases.
      - dependency-name: "@babel/eslint-parser"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"    
    labels:
      - "type:maintenance"
      - "dependencies"
      - "pr:daveit"
