
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"  
    open-pull-requests-limit: 10
    labels:
      - "pr:e2e"
      - "type:maintenance"
      - "dependencies"
      - "pr:daveit"
      - "pr:platform"
    ignore:
      - dependency-name: "@playwright/test" #we source the container instead of the dependency in CI

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"    
    labels:
      - "type:maintenance"
      - "dependencies"
      - "pr:daveit"
