name: "e2e"
on:
  workflow_dispatch:
    inputs: 
      version:
        description: 'Which branch do you want to test?' # Limited to branch for now
        required: false
        default: 'master' 
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - name: Run the e2e tests
        run: npm run test:e2e:ci
