name: "pr-platform"
on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  e2e-full:
    if: ${{ github.event.label.name == 'pr:platform' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 14
          - 16
          - 18
        architecture:
          - x64
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm install
      - run: npm test
      - run: npm run lint -- --quiet
